python MOcall_BT.py 1
python BT_ON_OFF_Test1.py 1
python WiFi_on_off_Test1.py 1
python Camera_Preview_Test.py 1
python mo_call.py 1
python Videotest.py 1
python sms.py 1
python Airplanemode_call.py 1
python Airplanemode_sms.py 1
python BT_ON_OFF_Test1.py 1
python MOcall_audio.py 1
python MOcall_sms.py 1
python MOcall_video.py 1
python MOcall_wifi.py 1
python MOcall_BT.py 5
python BT_ON_OFF_Test1.py 5
python WiFi_on_off_Test1.py 5
python Camera_Preview_Test.py 5
python mo_call.py 5
python Videotest.py 5
python sms.py 5
python Wifi_Connect_preset.py 5
python MOcall_hotspot_alarm_calender.py 5
python Airplanemode_call.py 5
python Airplanemode_sms.py 5
python BT_ON_OFF_Test1.py 5
python MOcall_audio.py 5
python MOcall_sms.py 5
python MOcall_video.py 5
python MOcall_wifi.py 5
python MOcall_BT.py 15
python BT_ON_OFF_Test1.py 15
python WiFi_on_off_Test1.py 15
python Camera_Preview_Test.py 15
python mo_call.py 15
python Videotest.py 15
python sms.py 15
python BT_ON_OFF_Test1.py 15
python MOcall_audio.py 15
python MOcall_sms.py 15
python MOcall_video.py 15
python MOcall_wifi.py 15
python MOcall_BT.py 100
python BT_ON_OFF_Test1.py 100
python WiFi_on_off_Test1.py 100
python Camera_Preview_Test.py 100
python mo_call.py 100
python Videotest.py 100
python sms.py 100
python BT_ON_OFF_Test1.py 100
python MOcall_audio.py 100
python MOcall_sms.py 100
python MOcall_video.py 100
python MOcall_wifi.py 100
python MOcall_Runall.py 100
python Airplanemode_call.py 100
python Airplanemode_sms.py 100
python MOcall_hotspot_alarm_calender.py 100

